### PR TITLE
If this is true it currently fails on CentOS 5.x

### PR DESCRIPTION
**Pull request by stanlemon**

### CODE REVIEW

**Comment by cmluciano** [comment]
I did some  digging and it does appear that sslverify was kind of borked in centos-5. That said I don't know if this was ever fixed and as jtimberman pointed out, this should not be the default for all rhel versions.

**Comment by cmluciano** [comment]
@stanlemon Which would like to resubmit this for centos-5 only?

**Comment by stanlemon** [comment]
@cmluciano I'm no longer using a centos5 setup so this less relevant to me now. Would love to help but it's no longer in scope for me at work.

**Comment by cmluciano** [comment]
Thanks @stanlemon. I will close this for now. If someone requires centos-5 in the future, I would be happy to add it.

**Pull request closed without merging**
